image: ruby:2.3

cache:
  paths:
  - vendor/

before_script:
  - bundle install --path vendor

pages:
  stage: deploy
  script:
  - mkdir .public
  - bundle exec jekyll build -d .public
  - mv .public public
  artifacts:
    paths:
    - public
